version: '3.4'

services:

  apidb:
    container_name: apidb
    environment:
        MSSQL_SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"

    restart: always
    ports:
        - "1433:1433"    
    volumes:
      - sqlvolume:/var/opt/mssql/data

 

  angularauthapi:
    container_name: angularauthapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlServerConnstr= Server=apidb;Database=ApiDb; User Id= SA ;Password= SwN12345678"
    depends_on:
      - apidb
    ports:
      - "8011:80"
