version: '3.4'

services:

  apidb:
    image: mcr.microsoft.com/mssql/server:2017-latest


  angularauthapi:
    image: ${DOCKER_REGISTRY-}angularauthapi
    build:
      context: .
      dockerfile: AngularAuthAPI/Dockerfile

volumes:
  sqlvolume: