version: '3.4'

services:

  apidb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  jwtdb:
    image: mcr.microsoft.com/mssql/server:2017-latest



  tokenbaseduserapi:
    image: ${DOCKER_REGISTRY-}tokenbaseduserapi
    build:
      context: .
      dockerfile: TokenBasedUserAPI/Dockerfile

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Product.API/Dockerfile

  shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: ShoppingCart.API/Dockerfile

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Payment.API/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order.API/Dockerfile

  couponservice.api:
    image: ${DOCKER_REGISTRY-}couponserviceapi
    build:
      context: .
      dockerfile: CouponService.API/Dockerfile

  product.grpcservice:
    image: ${DOCKER_REGISTRY-}productgrpcservice
    build:
      context: .
      dockerfile: GRPCServices/Product.GrpcService/Dockerfile

  reviews.api:
    image: ${DOCKER_REGISTRY-}reviewsapi
    build:
      context: .
      dockerfile: Reviews.API/Dockerfile

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: APIGateway/Ocelot.APIGateway/Dockerfile

volumes:
  sqlvolume:
  JWTvolume:









